### ISSUE TITLE
Details from pending transactions does not show the message

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-explorer#57]
Problem:
Send a transactions with a message. Inspect pending messages and click details. Message text is not shown.

Expected:
Details show the message in the same way it is shown for transactions already stored on chain.

**Comment by jjos2372** [comment]
This should be fixed already when the node is v3.3 or higher. Please check with the testnet version and soon with the mainnet upgrade.

**Comment by deleterium** [comment]
I think i was not clear. It is not working in testnet right now.

Here the pending transaction, clicked into details but the message is not displayed.
![Pending](https://deleterium.info/pending2.png)

Minutes later, the same transaction show the details and the message.
![Done](https://deleterium.info/done2.png)

**Comment by deleterium** [comment]
@jjos2372 So you can check that the issue still there, if it is supposed to show the attachments on pending transactions.

**Comment by jjos2372** [comment]
Reopening to investigate.

**Comment by pir8radio** [comment]
testing the fix for this on https://explorer.notallmine.net  if you can test again and let me know if what you were seeing is fixed?  Trying to close out some of these old issues..  :-)

**Comment by pir8radio** [comment]
added in latest PR. https://github.com/signum-network/signum-explorer/pull/178
